### PR TITLE
Upgrade version from 2.1.11 to 2.7.1

### PR DESCRIPTION
**Pull request by guikcd**
Hi folks,

Please consider upgrading the wiremock version :)

### CODE REVIEW

**Comment by plouc** [comment]
Hi,

Thank you for the update, can you also update the readme please ?

**Comment by guikcd** [comment]
:white_check_mark:

**Comment by plouc** [comment]
Thank you @guikcd

**Comment by guikcd** [comment]
Maybe your forgot to generate tag for this version on https://hub.docker.com/r/ekino/wiremock/tags/ ?

**Comment by plouc** [comment]
@guikcd, done

**Pull request merged**
